//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewULCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shows
    {
        public int SchowId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ShoImage { get; set; }
        public int Length { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ScheduledId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Schedules Schedules { get; set; }
    }
}
